### ISSUE TITLE
Add more stuff and become part of sindresorhus/awesome

### ISSUE THREAD

**Issue by maehr** [dh-tech/awesome-digital-humanities#11]
Hi there

I like your list and as a DH scholar I think it's important to have such a resource. To make it even better I would like to merge my [wiki](<https://github.com/maehr/awesome-digital-history/wiki>) (and its entries) into this list and get it on the official list of <https://github.com/sindresorhus/awesome>.
What do you think? Anyone want's to help?
Cheers
moritz

PS: I already merged <https://github.com/maehr/awesome-academic-writing> into <https://github.com/writing-resources/awesome-scientific-writing>. Here's our reasoning behind this step: <https://github.com/sindresorhus/awesome/pull/1700#issuecomment-601843528>

**Comment by maehr** [comment]
@robcast Thank you for merging my PR. If you activate the gh pages on root, a jekyll site will be published too.

To become part of the official awwsome list repo, the list must pass all tests of awesome-lint. 

```bash
npx awesome-lint
- Linting
✖ Linting

  README.md:1:1
  ✖  1:1  The repository should have a description                     remark-lint:awesome-github
  ✖  1:1  The repository should have "awesome" as a GitHub topic       remark-lint:awesome-github
  ✖  1:1  The repository should have "awesome-list" as a GitHub topic  remark-lint:awesome-github

  3 errors
```

As an external contributor, I cannot add descriptions, etc.

If I can be of any assistance, please let me know.

Cheers,
moritz

**Comment by robcast** [comment]
Sorry, again, for taking so long to get your PR merged. I just found that I don't have permission, yet, to change the repo topic, but I'll keep on it ;-)

**Comment by maehr** [comment]
@diegosiqueir4 If you do have some time to spare, you could probably fix these issues in a sec or two 😇.
Cheers
Moritz

**Comment by diegosiqueir4** [comment]
@maehr I am also only an external contributor and have no right to modify the repository. Maybe @jdamerow can fix it (*or give us enough power to do it*). Cheers!

**Comment by jdamerow** [comment]
I've fixed the issue the linter complained about. Not sure how to restart the actions but they should pass now. GH pages are here: https://dh-tech.github.io/awesome-dhtools/

**Comment by maehr** [comment]
@jdamerow there are still some things that need fixing before we can become part of the official awesome list:

- the default branch should be named `main` instead of `master` (more inclusive language)
- more topics should be added to the repo (like digital-humanities dh etc.)

I am working on a pull request over here https://github.com/sindresorhus/awesome/pull/2155

Feel free to help.
Cheers
Moritz

**Comment by jdamerow** [comment]
@diegosiqueir4 and @maehr do you want to become maintainers for this repo? If so, I'll give you admin rights on the repo. We're trying to distribute the load a little better :) 

Also, I just renamed the master branch to main.

**Comment by maehr** [comment]
@jdamerow I would love to help and to become a maintainer. Before I get involved, it would be nice if you could set up some guidelines for dealing with issues and pull requests. Clear and consistent guidelines help to defuse conflicts.

**Comment by diegosiqueir4** [comment]
Hi @jdamerow I am also interested in being one of the maintainers of this repository. I agree with @maehr, guidelines can facilitate solving future conflicts.

**Comment by jdamerow** [comment]
Great! We have the DHTech steering committee meeting next week and will talk about some guidelines. If you have any thoughts on it, let me know! :)

**Comment by jdamerow** [comment]
@maehr @diegosiqueir4 We've written up some (very short) guidelines here: https://github.com/dh-tech/awesome-dhtools/wiki/Maintainer-Guidelines

Please let us know if you have questions that are not covered or if you would like to change something. You are probably in a better position than we are to say what needs to be included or not :)

**Comment by jdamerow** [comment]
@maehr @diegosiqueir4 I've made both of you maintainers. I hope this gives you all the permissions you need! If not, let me know!

**Comment by maehr** [comment]
Hi there, I don't have time at the moment to fix the list according to the reviews. If someone does have time it would be nice 🙂 See https://github.com/sindresorhus/awesome/pull/2155

**Comment by jdamerow** [comment]
@maehr @diegosiqueir4 if it's alright with you, we would list you as maintainers on our DHTech website and write up a short news post about it. Does that sound ok?

**Comment by maehr** [comment]
> @maehr @diegosiqueir4 if it's alright with you, we would list you as maintainers on our DHTech website and write up a short news post about it. Does that sound ok?

Absolutely 🤗

**Comment by diegosiqueir4** [comment]
> @maehr @diegosiqueir4 if it's alright with you, we would list you as maintainers on our DHTech website and write up a short news post about it. Does that sound ok?

Sure! :)

**Comment by maehr** [comment]
Hey guys, what do you think about these inputs:

> The list should be named `Awesome Digital Humanities` (repo too).

_Originally posted by @sindresorhus in https://github.com/sindresorhus/awesome/issues/2155#issuecomment-1144762542_

> Your entry here should include a short description about the project/theme of the list. It should not describe the list itself. The first character should be uppercase and the description should end in a dot. It should be an objective description and not a tagline or marketing blurb.

_Originally posted by @sindresorhus in https://github.com/sindresorhus/awesome/issues/2155#issuecomment-1144762783_

**Comment by maltevogl** [comment]
I think we can safely rename the repo and list. Its seems the existing description is to short?

**Comment by maehr** [comment]
> I think we can safely rename the repo and list. Its seems the existing description is to short?

Is there a repo owner who can change the name accordingly?

**Comment by maltevogl** [comment]
done :-) let me know if other things are needed

**Comment by maltevogl** [comment]
ahh settings for the website need to be recompiled or so I guess....

**Comment by maehr** [comment]
> done :-) let me know if other things are needed

Would you mind lower case everything? Most lists do not contain upper case letters.

**Comment by maltevogl** [comment]
OK, done. Do we need to change the name in the README headline as well? And we need to advertise the new website url...

**Comment by maehr** [comment]
> Stale issue message

Still waiting for https://github.com/sindresorhus/awesome/pull/2155

**Comment by maehr** [comment]
Our PR was merged and we are a official part of awesome lists!

**Comment by maehr** [comment]
Reopened due to misunderstanding in https://github.com/sindresorhus/awesome/pull/2155
