### ISSUE TITLE
Add https://datacommons.org/

### ISSUE THREAD

**Issue by maehr** [dh-tech/awesome-digital-humanities#36]
**Item**

- [Data Commons](https://datacommons.org/) - Data Commons aggregates data from a [wide range of sources](https://docs.datacommons.org/datasets/) into a unified database to make it more accessible and useful..

**Rationale for the change**

It's a great additional data source.

Please note that this project is released with a
[Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in this
project you agree to abide by its terms.

**Comment by maehr** [comment]
@diegosiqueir4 What do you think of this resource?

**Comment by diegosiqueir4** [comment]
> @diegosiqueir4 What do you think of this resource?

@maehr I think it will make a good addition to the list. Would you add it or do you would like me to?

**Comment by maehr** [comment]
Thanks for offering to make the pull request. That would be great.

**Comment by diegosiqueir4** [comment]
> Thanks for offering to make the pull request. That would be great.

Done in pull request #37 :)
